/* tslint:disable */
/* eslint-disable */
/**
 * Logic Tool
 * API for managing the Logic Tool
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dmacau@campus.fct.unl.pt
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MarkComponent } from './MarkComponent';
import {
    MarkComponentFromJSON,
    MarkComponentFromJSONTyped,
    MarkComponentToJSON,
} from './MarkComponent';

/**
 * 
 * @export
 * @interface ExpComponent
 */
export interface ExpComponent {
    /**
     * 
     * @type {string}
     * @memberof ExpComponent
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpComponent
     */
    value?: string;
    /**
     * 
     * @type {MarkComponent}
     * @memberof ExpComponent
     */
    mark?: MarkComponent;
}

/**
 * Check if a given object implements the ExpComponent interface.
 */
export function instanceOfExpComponent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExpComponentFromJSON(json: any): ExpComponent {
    return ExpComponentFromJSONTyped(json, false);
}

export function ExpComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpComponent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'mark': !exists(json, 'mark') ? undefined : MarkComponentFromJSON(json['mark']),
    };
}

export function ExpComponentToJSON(value?: ExpComponent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'value': value.value,
        'mark': MarkComponentToJSON(value.mark),
    };
}

