/* tslint:disable */
/* eslint-disable */
/**
 * Logic Tool
 * API for managing the Logic Tool
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dmacau@campus.fct.unl.pt
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Component } from './Component';
import {
    ComponentFromJSON,
    ComponentFromJSONTyped,
    ComponentToJSON,
} from './Component';

/**
 * 
 * @export
 * @interface MarkComponent
 */
export interface MarkComponent extends Component {
    /**
     * 
     * @type {string}
     * @memberof MarkComponent
     */
    value?: string;
}

/**
 * Check if a given object implements the MarkComponent interface.
 */
export function instanceOfMarkComponent(value: object): boolean {
    return true;
}

export function MarkComponentFromJSON(json: any): MarkComponent {
    return MarkComponentFromJSONTyped(json, false);
}

export function MarkComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkComponent {
    if (json == null) {
        return json;
    }
    return {
        ...ComponentFromJSONTyped(json, ignoreDiscriminator),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MarkComponentToJSON(value?: MarkComponent | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...ComponentToJSON(value),
        'value': value['value'],
    };
}

