/* tslint:disable */
/* eslint-disable */
/**
 * Logic Tool
 * API for managing the Logic Tool
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dmacau@campus.fct.unl.pt
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpComponent } from './ExpComponent';
import {
    ExpComponentFromJSON,
    ExpComponentFromJSONTyped,
    ExpComponentToJSON,
} from './ExpComponent';
import type { MarkComponent } from './MarkComponent';
import {
    MarkComponentFromJSON,
    MarkComponentFromJSONTyped,
    MarkComponentToJSON,
} from './MarkComponent';
import type { RuleComponent } from './RuleComponent';
import {
    RuleComponentFromJSON,
    RuleComponentFromJSONTyped,
    RuleComponentToJSON,
} from './RuleComponent';

/**
 * 
 * @export
 * @interface TreeComponent
 */
export interface TreeComponent {
    /**
     * 
     * @type {string}
     * @memberof TreeComponent
     */
    type?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TreeComponent
     */
    errors?: { [key: string]: any; };
    /**
     * 
     * @type {ExpComponent}
     * @memberof TreeComponent
     */
    conclusion?: ExpComponent;
    /**
     * 
     * @type {Array<MarkComponent>}
     * @memberof TreeComponent
     */
    marks?: Array<MarkComponent>;
    /**
     * 
     * @type {RuleComponent}
     * @memberof TreeComponent
     */
    rule?: RuleComponent;
    /**
     * 
     * @type {any}
     * @memberof TreeComponent
     */
    hypotheses?: any;
    /**
     * 
     * @type {boolean}
     * @memberof TreeComponent
     */
    genHints?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof TreeComponent
     */
    env?: { [key: string]: string; };
}

/**
 * Check if a given object implements the TreeComponent interface.
 */
export function instanceOfTreeComponent(value: object): boolean {
    return true;
}

export function TreeComponentFromJSON(json: any): TreeComponent {
    return TreeComponentFromJSONTyped(json, false);
}

export function TreeComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'errors': json['errors'] == null ? undefined : json['errors'],
        'conclusion': json['conclusion'] == null ? undefined : ExpComponentFromJSON(json['conclusion']),
        'marks': json['marks'] == null ? undefined : ((json['marks'] as Array<any>).map(MarkComponentFromJSON)),
        'rule': json['rule'] == null ? undefined : RuleComponentFromJSON(json['rule']),
        'hypotheses': json['hypotheses'] == null ? undefined : json['hypotheses'],
        'genHints': json['genHints'] == null ? undefined : json['genHints'],
        'env': json['env'] == null ? undefined : json['env'],
    };
}

export function TreeComponentToJSON(value?: TreeComponent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'errors': value['errors'],
        'conclusion': ExpComponentToJSON(value['conclusion']),
        'marks': value['marks'] == null ? undefined : ((value['marks'] as Array<any>).map(MarkComponentToJSON)),
        'rule': RuleComponentToJSON(value['rule']),
        'hypotheses': value['hypotheses'],
        'genHints': value['genHints'],
        'env': value['env'],
    };
}

