/* tslint:disable */
/* eslint-disable */
/**
 * Logic Tool
 * API for managing the Logic Tool
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dmacau@campus.fct.unl.pt
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarkComponent } from './MarkComponent';
import {
    MarkComponentFromJSON,
    MarkComponentFromJSONTyped,
    MarkComponentToJSON,
} from './MarkComponent';

/**
 * 
 * @export
 * @interface ExpComponent
 */
export interface ExpComponent {
    /**
     * 
     * @type {string}
     * @memberof ExpComponent
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpComponent
     */
    value?: string;
    /**
     * 
     * @type {MarkComponent}
     * @memberof ExpComponent
     */
    mark?: MarkComponent;
    /**
     * 
     * @type {boolean}
     * @memberof ExpComponent
     */
    genHints?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ExpComponent
     */
    env?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ExpComponent interface.
 */
export function instanceOfExpComponent(value: object): boolean {
    return true;
}

export function ExpComponentFromJSON(json: any): ExpComponent {
    return ExpComponentFromJSONTyped(json, false);
}

export function ExpComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'mark': json['mark'] == null ? undefined : MarkComponentFromJSON(json['mark']),
        'genHints': json['genHints'] == null ? undefined : json['genHints'],
        'env': json['env'] == null ? undefined : json['env'],
    };
}

export function ExpComponentToJSON(value?: ExpComponent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
        'mark': MarkComponentToJSON(value['mark']),
        'genHints': value['genHints'],
        'env': value['env'],
    };
}

