package logic.algorithm;

public enum ERule {

    INTRO_CONJUNCTION,
    ELIM_CONJUNCTION_LEFT,
    ELIM_CONJUNCTION_RIGHT,
    ELIM_IMPLICATION,
    INTRO_DISJUNCTION_LEFT,
    INTRO_DISJUNCTION_RIGHT,
    INTRO_NEGATION,
    ELIM_NEGATION,
    ELIM_DISJUNCTION,
    INTRO_IMPLICATION,
    ABSURDITY,
    ELIM_UNIVERSAL,
    ELIM_EXISTENTIAL,
    INTRO_UNIVERSAL,
    INTRO_EXISTENTIAL;

}
