/* Generated By:JavaCC: Do not edit this line. ExpressionsParser.java */
package parser;

import ast.logic.ASTLiteral;
import ast.symbols.*;
import ast.logic.*;
import ast.types.ASTBool;
import ast.Exp;import ast.types.ASTConstant;import ast.types.ASTPred;import ast.types.ASTVariable;

public class ExpressionsParser implements ExpressionsParserConstants {

/*
* Parser for propositional expressions
*/
  final public Exp parseProp() throws ParseException {
    Exp e;
    e = propLogicSequences();
    jj_consume_token(0);
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Exp propLogicSequences() throws ParseException {
    ASTSequence exps;
    Exp e;
    e = propLogicEquivalences();
    jj_consume_token(PERIOD);
                                           exps = new ASTSequence(e);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAR:
      case TRUE:
      case FALSE:
      case NOT:
      case VARIABLE:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      e = propLogicEquivalences();
      jj_consume_token(PERIOD);
                                             exps.addExp(e);
    }
      {if (true) return exps;}
    throw new Error("Missing return statement in function");
  }

  final private Exp propLogicEquivalences() throws ParseException {
    Exp e1, e2;
    e1 = propLogicBinary();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CMP:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(CMP);
      e2 = propLogicBinary();
                                                            e1 = new ASTComp(e1, e2);
    }
      {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  final private Exp propLogicBinary() throws ParseException {
    Exp e1, e2;
    e1 = propLogicUnary();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
      case IMPLICATION:
      case BICONDITIONAL:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        jj_consume_token(AND);
        e2 = propLogicUnary();
                                      e1 = new ASTAnd(e1, e2);
        break;
      case OR:
        jj_consume_token(OR);
        e2 = propLogicUnary();
                                     e1 = new ASTOr(e1, e2);
        break;
      case IMPLICATION:
        jj_consume_token(IMPLICATION);
        e2 = propLogicUnary();
                                              e1 = new ASTImplication(e1, e2);
        break;
      case BICONDITIONAL:
        jj_consume_token(BICONDITIONAL);
        e2 = propLogicUnary();
                                                e1 = new ASTBiconditional(e1, e2);
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  final private Exp propLogicUnary() throws ParseException {
    Token t;
    Exp e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
      jj_consume_token(TRUE);
             {if (true) return new ASTBool(true);}
      break;
    case FALSE:
      jj_consume_token(FALSE);
              {if (true) return new ASTBool(false);}
      break;
    case NOT:
      jj_consume_token(NOT);
      e = propLogicUnary();
                                 {if (true) return new ASTNot(e);}
      break;
    case LPAR:
      jj_consume_token(LPAR);
      e = propLogicBinary();
      jj_consume_token(RPAR);
                                          {if (true) return new ASTParenthesis(e);}
      break;
    case VARIABLE:
      t = jj_consume_token(VARIABLE);
                     {if (true) return new ASTLiteral(t.image);}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/*
* Parser for first-order expressions
*/
  final public Exp parseFOL() throws ParseException {
    Exp e;
    e = folLogicSequences();
    jj_consume_token(0);
      {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Exp folLogicSequences() throws ParseException {
    ASTSequence exps;
    Exp e;
    e = folLogicExpressions();
    jj_consume_token(PERIOD);
                                         exps = new ASTSequence(e);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAR:
      case TRUE:
      case FALSE:
      case NOT:
      case PREDICATE:
      case DEL_PREDICATE:
      case UNIVERSAL:
      case EXISTENTIAL:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      e = folLogicExpressions();
      jj_consume_token(PERIOD);
                                           exps.addExp(e);
    }
      {if (true) return exps;}
    throw new Error("Missing return statement in function");
  }

  final private Exp folLogicExpressions() throws ParseException {
    Token t;
    Exp e1, e2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEL_PREDICATE:
      t = jj_consume_token(DEL_PREDICATE);
                          {if (true) return new ASTDelPred(t.image);}
      break;
    case LPAR:
    case TRUE:
    case FALSE:
    case NOT:
    case PREDICATE:
    case UNIVERSAL:
    case EXISTENTIAL:
      e1 = folLogicBinary();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CMP:
        jj_consume_token(CMP);
        e2 = folLogicBinary();
                                                            e1 = new ASTComp(e1, e2);
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      {if (true) return e1;}
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Exp folLogicBinary() throws ParseException {
    Exp e1, e2;
    e1 = folLogicUnary();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
      case IMPLICATION:
      case BICONDITIONAL:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        jj_consume_token(AND);
        e2 = folLogicUnary();
                                     e1 = new ASTAnd(e1, e2);
        break;
      case OR:
        jj_consume_token(OR);
        e2 = folLogicUnary();
                                    e1 = new ASTOr(e1, e2);
        break;
      case IMPLICATION:
        jj_consume_token(IMPLICATION);
        e2 = folLogicUnary();
                                             e1 = new ASTImplication(e1, e2);
        break;
      case BICONDITIONAL:
        jj_consume_token(BICONDITIONAL);
        e2 = folLogicUnary();
                                               e1 = new ASTBiconditional(e1, e2);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  final private Exp folLogicUnary() throws ParseException {
    Token t;
    Exp e, e1;
    ASTPred pred;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
      jj_consume_token(TRUE);
             {if (true) return new ASTBool(true);}
      break;
    case FALSE:
      jj_consume_token(FALSE);
              {if (true) return new ASTBool(false);}
      break;
    case NOT:
      jj_consume_token(NOT);
      e = folLogicUnary();
                                {if (true) return new ASTNot(e);}
      break;
    case LPAR:
      jj_consume_token(LPAR);
      e = folLogicBinary();
      jj_consume_token(RPAR);
                                         {if (true) return new ASTParenthesis(e);}
      break;
    case EXISTENTIAL:
      jj_consume_token(EXISTENTIAL);
      e = folTerm();
      e1 = folLogicUnary();
                                                      {if (true) return new ASTExistential(e, e1);}
      break;
    case UNIVERSAL:
      jj_consume_token(UNIVERSAL);
      e = folTerm();
      e1 = folLogicUnary();
                                                     {if (true) return new ASTUniversal(e, e1);}
      break;
    case PREDICATE:
      t = jj_consume_token(PREDICATE);
                      pred = new ASTPred(t.image);
      jj_consume_token(LPAR);
      e = folTerm();
                           pred.addTerm(e);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[10] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        e = folTerm();
                                                                        pred.addTerm(e);
      }
      jj_consume_token(RPAR);
                                                                                                      {if (true) return pred;}
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Exp folTerm() throws ParseException {
   Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARIABLE:
      t = jj_consume_token(VARIABLE);
                    {if (true) return new ASTVariable(t.image);}
      break;
    case CONSTANT:
      t = jj_consume_token(CONSTANT);
                    {if (true) return new ASTConstant(t.image);}
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public ExpressionsParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[13];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x81680,0x800,0x1e000,0x1e000,0x81680,0xc61680,0x800,0xc61680,0x1e000,0x1e000,0x200000,0xc21680,0x1080000,};
   }

  /** Constructor with InputStream. */
  public ExpressionsParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ExpressionsParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ExpressionsParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ExpressionsParser(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new ExpressionsParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ExpressionsParser(ExpressionsParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ExpressionsParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[25];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 13; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 25; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
