/* Generated By:JavaCC: Do not edit this line. ExpressionsParserConstants.java */
package parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTER = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int LPAR = 7;
  /** RegularExpression Id. */
  int RPAR = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int CMP = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int IMPLICATION = 15;
  /** RegularExpression Id. */
  int BICONDITIONAL = 16;
  /** RegularExpression Id. */
  int PREDICATE = 17;
  /** RegularExpression Id. */
  int DEL_PREDICATE = 18;
  /** RegularExpression Id. */
  int VARIABLE = 19;
  /** RegularExpression Id. */
  int PERIOD = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int UNIVERSAL = 22;
  /** RegularExpression Id. */
  int EXISTENTIAL = 23;
  /** RegularExpression Id. */
  int CONSTANT = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"\\u22a4\"",
    "\"\\u22a5\"",
    "\"\\u2261\"",
    "\"\\u00ac\"",
    "\"\\u2227\"",
    "\"\\u2228\"",
    "\"\\u2192\"",
    "\"\\u2194\"",
    "<PREDICATE>",
    "<DEL_PREDICATE>",
    "<VARIABLE>",
    "\".\"",
    "\",\"",
    "\"\\u2200\"",
    "\"\\u2203\"",
    "<CONSTANT>",
  };

}
