/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTER = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int BOOL = 7;
  /** RegularExpression Id. */
  int UNIT = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int CMP = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int DIFF = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int IMPLICATION = 19;
  /** RegularExpression Id. */
  int EQUIVALENT = 20;
  /** RegularExpression Id. */
  int MODELS = 21;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 22;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int LITERAL = 25;
  /** RegularExpression Id. */
  int TEXT = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"bool\"",
    "\"unit\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\"==\"",
    "\"~\"",
    "\"&&\"",
    "\"||\"",
    "\"!=\"",
    "\";\"",
    "\"->\"",
    "\"<=>\"",
    "\"|=\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<LITERAL>",
    "<TEXT>",
  };

}
